### ISSUE TITLE
Generate OpenAPI spec for prunner API from Go code

### ISSUE THREAD

**Issue by hlubek** [Flowpack/prunner#18]
Scenario: API users want to read about the REST API

**Comment by Polo2** [comment]
Hello there,

I'm Paul, from [Bump](https://bump.sh) team, we're actually talking on Intercom on bump website.

As soon as your OpenAPI specification file is ready, and maybe accessible with an url, you can easily preview it:
https://bump.sh/#url-preview , available during 1 hour.

If generated documentation suits you, feel free to sign up and create your documentation from this OpenAPI specification.

From webpage, you'll have to upload a `yaml` or `json` file, but it's also possible to deploy your spec from your terminal with our [CI tools](https://help.bump.sh/continuous-integration).

Please don't hesitate to contact us if you need some support.

PS: About pricing, I guess you would be interested to know that we 💙  open source, and [every resources are free](https://bump.sh/pricing) for open source project

Happy API documentation!
