### ISSUE TITLE
Improvement: cancel queued job executions

### ISSUE THREAD

**Issue by erickloss** [Flowpack/prunner#40]
For now it only seems to be possible to cancel running jobs. It would be great to have the possibility to cancel jobs that are queued and not jet in execution.

Idea:
1. The cancel job by ID REST endpoint should support cancellation of jobs independently of their queueing state.
2. The prunner UI should also provide the cancel button for queued jobs.

Any opinions about that feature request?

Cheers
Eric

**Comment by Sebobo** [comment]
Somehow we ended up with canceled queued jobs, not sure how we got there, as I thought it was not really possible... 

Of course this confused all the UI parts.

**Comment by Sebobo** [comment]
@hlubek I checked the code and currently there is an error thrown when trying to cancel a job that hasn't been started. 
Can we not just ignore that and allow cancelling the job?
We have the problem that editors queue a lot of jobs and then change their mind.

**Comment by hlubek** [comment]
Yeah sure, that makes sense.
I'd expect it to be kept and marked as canceled though.
I'll add a test to make sure a queued and not yet started job can be canceled.

**Comment by hlubek** [comment]
@Sebobo @erickloss Does #43 fix the issue for you?

**Comment by Sebobo** [comment]
@hlubek thx! Looks great.
